# Generated by Django 3.2.9 on 2022-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.FloatField(default=0.0)),
                ('min_time', models.FloatField(default=0.0)),
                ('average_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('task_id', models.UUIDField()),
                ('program_language', models.PositiveSmallIntegerField(choices=[('1', 'Python')], default=1)),
                ('solution', models.JSONField(default=str)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSystemLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveBigIntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField(default=0.0)),
                ('ram', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLoadInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('task_id', models.UUIDField()),
                ('program_language', models.PositiveSmallIntegerField(choices=[('1', 'Python')], default=1)),
                ('solution', models.JSONField(default=str)),
            ],
        ),
    ]
