# Generated by Django 3.2.9 on 2022-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparam',
            name='test_case',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='operatingtime',
            name='average_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='operatingtime',
            name='max_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='operatingtime',
            name='min_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='solution',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='task_id',
            field=models.CharField(default='TASK ID', max_length=128),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='user_id',
            field=models.CharField(default='ID', max_length=128),
        ),
        migrations.AddField(
            model_name='reportsystemload',
            name='c',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resourceload',
            name='cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resourceload',
            name='ram',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='taskparams',
            name='solution',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='taskparams',
            name='task_id',
            field=models.CharField(default='TASK ID', max_length=128),
        ),
        migrations.AddField(
            model_name='taskparams',
            name='user_id',
            field=models.CharField(default='ID', max_length=128),
        ),
    ]
