# Generated by Django 3.2.9 on 2022-01-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceLoad',
        ),
        migrations.AddField(
            model_name='caseparam',
            name='average_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caseparam',
            name='max_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caseparam',
            name='min_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caseparam',
            name='resource_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_server.systemloadinformation'),
        ),
        migrations.AddField(
            model_name='reportsystemload',
            name='cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reportsystemload',
            name='ram',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='max_cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='max_ram',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='min_cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='min_ram',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='taskparams',
            name='case_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_server.caseparam'),
        ),
    ]
