# Generated by Django 3.2.9 on 2022-01-20 17:23

from django.db import migrations, models
import test_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_server', '0002_auto_20220120_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsystemload',
            name='c',
        ),
        migrations.AddField(
            model_name='reportsystemload',
            name='time_spent',
            field=models.PositiveBigIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='max_params',
            field=models.JSONField(default={test_server.models.ResourceLoad}),
        ),
        migrations.AddField(
            model_name='systemloadinformation',
            name='min_params',
            field=models.JSONField(default={test_server.models.ResourceLoad}),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='user_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='taskparams',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='taskparams',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
