# Generated by Django 3.2.9 on 2022-01-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_server', '0003_auto_20220120_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemloadinformation',
            name='min_params',
        ),
        migrations.AddField(
            model_name='processingresult',
            name='program_language',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Python')], default=1),
        ),
        migrations.AddField(
            model_name='taskparams',
            name='program_language',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Python')], default=1),
        ),
        migrations.AlterField(
            model_name='systemloadinformation',
            name='max_params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_server.resourceload'),
        ),
    ]
