# Generated by Django 3.2.9 on 2022-01-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_server', '0004_auto_20220120_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemloadinformation',
            name='max_params',
        ),
    ]
