# Generated by Django 3.2.9 on 2021-11-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatingTime',
        ),
    ]
