# Generated by Django 3.2.9 on 2021-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_client', '0002_delete_operatingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('task_id', models.CharField(max_length=30)),
                ('program_language', models.CharField(max_length=15)),
                ('testing_stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_status', models.IntegerField()),
                ('task_id', models.CharField(max_length=30)),
                ('program_language', models.CharField(max_length=15)),
            ],
        ),
    ]
