# Generated by Django 3.2.9 on 2021-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_checksend_resultsend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksend',
            old_name='program_language',
            new_name='program_lang',
        ),
        migrations.RenameField(
            model_name='resultsend',
            old_name='program_language',
            new_name='program_lang',
        ),
    ]
