# Generated by Django 4.0.3 on 2022-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0005_auto_20211213_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksend',
            name='code_file',
            field=models.FileField(default='default.py', upload_to=''),
        ),
    ]
