# Generated by Django 4.0.3 on 2022-05-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0008_delete_checksendjson_rename_code_file_checksend_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.usertypes')),
            ],
        ),
    ]
