# Generated by Django 4.0.3 on 2022-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0009_usertypes_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypes',
            name='user_type',
            field=models.CharField(max_length=30),
        ),
    ]
