# Generated by Django 4.0.3 on 2022-05-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0013_alter_checksend_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_of_value', models.CharField(max_length=10)),
                ('mark_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='checksend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.users'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('task_description', models.TextField(unique=True)),
                ('test_data', models.CharField(max_length=500)),
                ('time_to_solve', models.IntegerField()),
                ('resource_load', models.CharField(max_length=300)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.marks')),
            ],
        ),
        migrations.AlterField(
            model_name='checksend',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.tasks'),
        ),
        migrations.AlterField(
            model_name='resultsend',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.tasks'),
        ),
    ]
