# Generated by Django 4.0.3 on 2022-05-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0016_rename_resulttest_completetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.users')),
            ],
        ),
        migrations.CreateModel(
            name='MarkedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigment_time', models.IntegerField()),
                ('time_solve_task', models.IntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.studentgroupinfo')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.studentgroupinfo')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.users')),
            ],
        ),
    ]
