# Generated by Django 4.0.3 on 2022-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0017_studentgroupinfo_markedtasks_groupcomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupinfo',
            name='group_name',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
