# Generated by Django 4.0.3 on 2022-05-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0019_rename_group_id_groupcomposition_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markedtasks',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='markedtasks',
            old_name='task_id',
            new_name='task',
        ),
    ]
