# Generated by Django 4.0.3 on 2022-05-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0020_rename_group_id_markedtasks_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcomposition',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupcomposition',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='markedtasks',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='markedtasks',
            old_name='task',
            new_name='task_id',
        ),
    ]
